# SPDX-FileCopyrightText: Copyright (c) 2023-2026 Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>
# SPDX-License-Identifier: MIT
---
version: 3

tasks:

  rs-run:
    cmds:
      - cargo run

  fmt:
    cmds:
      - poetry run ruff check deltaver tests --fix --fix-only
      - cargo fmt --all

  lint:
    cmds:
      - poetry run ruff check deltaver tests --select="F"
      - poetry run ruff check deltaver tests | poetry run ondivi
      - ./lint-venv/bin/flake8 deltaver tests | poetry run ondivi

  syntax-check:
    cmds:
      - poetry run ruff check deltaver tests --select=F --ignore=F401,F841
  
  type-check:
    cmds:
      - poetry run mypy deltaver tests

  test:
    env:
      TZ: UTC
    deps: [syntax-check,type-check]
    cmds:
      - poetry run pytest {{.CLI_ARGS}} -s -vv --cov=deltaver --cov-report=term-missing:skip-covered

  clean:
    cmds:
      - git clean -f -d -x
